## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'demo'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_demo become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_demo' #to modify
description = 'Demo files for plugin creation'

author = 'Author Name'
author-email = 'Author email'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyserial']
